### ISSUE TITLE
Issue with density_bands()

### ISSUE THREAD

**Issue by shadyamigo** [akoyabio/phenoptr#10]
I am using inform 2.4.4 and am trying use the density_bands method. Unfortunately I get the following error:
Error in distance$v[ix] : subscript out of bounds
I have tried to debug this myself without joy.
I am happy to provide sample data if required

Best wishes

**Comment by AB-Kent** [comment]
Can you post the complete error message with the traceback? Thanks!

**Comment by shadyamigo** [comment]
Thank you for responding
The error message is only:
Error in distance$v[ix] : subscript out of bounds
> traceback()
1: density_bands(path, list("CD8", "CD4", "Tregs"), positive = "Stroma", 
       negative = "Tumour")
Many thanks,

**Comment by AB-Kent** [comment]
Can you send me both cell seg data files (with locations in pixels and microns) and the corresponding segmentation map? (See my profile for email.) Thanks!
