### ISSUE TITLE
inForm data output analysis

### ISSUE THREAD

**Issue by hummingbirdbio** [akoyabio/phenoptr#11]
Would it be possible to have a tutorial on the best way to threshold data if not using the inForm software?

**Comment by AB-Kent** [comment]
I'm not sure what you have in mind, phenoptr is specifically for working with inForm output.

**Comment by hummingbirdbio** [comment]
Thanks Kent. Would you recommend that all thresholds for all markers are set from within inForm? I'm working with output from inForm for which no cell phenotypes have been set.

So when it comes to setting a threshold value for a given marker I'm trying to figure out how best to do that from within phenoptr.

Konrad Paszkiewicz, PhD
Chief Technology Officer
Hummingbird Bioscience Pte. Ltd.



NOTICE:  The information contained in this email and any document attached hereto is intended only for the named recipient(s). If you are not the intended recipient, nor the employee or agent responsible for delivering this message in confidence to the intended recipient(s), you are hereby notified that you have received this transmittal in error, and any review, dissemination, distribution or copying of this transmittal or its attachments is strictly prohibited. If you have received this transmittal and/or attachments in error, please notify me immediately by reply e-mail and then delete this message, including any attachments. Thank you for your cooperation.




________________________________

**Comment by AB-Kent** [comment]
Yes, phenoptr expects that phenotypes have been set with the inForm phenotyping step. There is no function in phenoptr which supports this.

**Comment by gcakoyabio** [comment]
Konrad,
My name is Grady Carlson and I am your technical applications specialist for Texas. Please feel free to contact me at gcarlson@akoyabio.com for more information about inForm and related software.
Thank you,
Grady
