### ISSUE TITLE
Parsing failures: count touch pairs

### ISSUE THREAD

**Issue by Athanasios72** [akoyabio/phenoptr#12]
Dear Kent,

I have been using phenoptr to calculate touch cell pairs in my OPAL stained tissue. I have two questions:
1) When using non-tissue segmented and tissue segmented data from InForm (2.3), does the same script give accurate results? Do I need to add any additional data files in the folder with data other than ....**.cell_seg_data.txt** and ....**binary_seg_maps.tif**?
I use this script for both:
"base_path <- '~/DATA/'
paths <- list_cell_seg_files(base_path)
files <- list_cell_seg_files(base_path)
pairs <- list(
  c('CD3CD4', 'CD3CD4FOXP3'),
  c('CD3CD4', 'CD3CD8'),
  c('CD3CD4', 'CD3DN')
)
touch_counts<- purrr::map_df(files, function(path) {
  count_touching_cells(path, pairs, write_images=FALSE)
})"

2) Using the above script with tissue segmented data files I often get the following error message when doing touch cell pair analysis:
"Warning: 91 parsing failures.
 row                                         col           expected actual                                                                                            file
1736 Distance from Tissue Category Edge (pixels) 1/0/T/F/TRUE/FALSE  287.0 'C:/Users/KoulisAthanasios/Documents/DATA/2692 tpan_[46199,14394]_cell_seg_data.txt''
.........."

Any feedback would be welcome.

Thank you.

Regards,

Athanasios

**Comment by AB-Kent** [comment]
1. count_touching_cells does not use tissue segmentation if it is not
provided in the call, so these should give comparable results.
2. If the errors are all for "Distance from Tissue Category Edge" this is
OK. The function that reads the data files (readr::read_tsv) tries to
determine the data type of each column from the first 1000 rows of data.
Sometimes the first 1000 rows are not representative; then there are
parsing errors on subsequent rows. In this case, the errors are for a
column you are not using so you can ignore them.

**Comment by Athanasios72** [comment]
Thank you. Your reply has really helped me out.
Regards,
Athanasios
