### ISSUE TITLE
Please update to the latest version of `phenoptr`.

### ISSUE THREAD

**Issue by lmunoz79** [akoyabio/phenoptr#14]
Please update to the latest version of `phenoptr`. The version you are using is over a year old and there have been many changes since then. Specifically, the `Cell ID` columns were added to the output of `find_nearest_distance` in [version 0.2.0](https://akoyabio.github.io/phenoptr/news/index.html#phenoptr-020).

You may also be interested in [`phenoptrReports`](https://akoyabio.github.io/phenoptrReports/index.html) which provides GUI front-ends to many `phenoptr` functions, giving access to `phenoptr` functionality without the need to program in R.

_Originally posted by @AB-Kent in https://github.com/akoyabio/phenoptr/issues/13#issuecomment-561174599_

Hi Kent
I've tried to update the package, but this is the message i get:
Warning in install.packages :
  package ‘phenoptr’ is not available (for R version 3.6.1)

Initially I installed the package as the Akoya website link directed so the process of installing the outdated version of phenoptr was automated.

**Comment by AB-Kent** [comment]
`phenoptr` is installed from Github, not from CRAN. Use the R commands
```
install.packages("devtools")
devtools::install_github("akoyabio/phenoptr")
```

**Comment by lmunoz79** [comment]
Hi Kent
Thanks for the prompt response.
I decided to put the command directly into R instead of R Studios and this is the output I got. It appears that the tiff package is causing issues

The downloaded binary packages are in
	/var/folders/cj/qkj7rjfd0074j9r1nrsv29340000gp/T//RtmpxY38br/downloaded_packages
> devtools::install_github("akoyabio/phenoptr")
Downloading GitHub repo akoyabio/phenoptr@master
These packages have more recent versions available.
Which would you like to update?

1: All                                  
2: CRAN packages only                   
3: None                                 
4: tiff (0.1-5 -> e29964f67...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
1
tiff (0.1-5 -> e29964f67...) [GitHub]
Skipping 1 packages ahead of CRAN: BiocGenerics
Downloading GitHub repo akoyabio/tiff@master
   checking DESCRIPTION meta-information ...j/qkj7rjfd0074j9r1nrsv29340000gp/T/RtmpxY38br/remotesb0e6c6ecde8/akoyabio-tiff-e29964f/DESCRIPTION’ ...
Installing package into ‘/Users/lmunozerazo/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘tiff’ ...
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c common.c -o common.o
In file included from common.c:1:
./common.h:5:10: fatal error: 'tiff.h' file not found
#include <tiff.h>
         ^~~~~~~~
1 error generated.
make: *** [common.o] Error 1
ERROR: compilation failed for package ‘tiff’
* removing ‘/Users/lmunozerazo/Library/R/3.6/library/tiff’
* restoring previous ‘/Users/lmunozerazo/Library/R/3.6/library/tiff’
Error: Failed to install 'phenoptr' from GitHub:
  Failed to install 'tiff' from GitHub:
  (converted from warning) installation of package ‘/var/folders/cj/qkj7rjfd0074j9r1nrsv29340000gp/T//RtmpxY38br/fileb0e8a26313/tiff_0.1.7.tar.gz’ had non-zero exit status

**Comment by lmunoz79** [comment]
I circumvented the issue by skipping the package updates section. Thanks for your help

**Comment by AB-Kent** [comment]
Yes, that is a good workaround though you won't be able to work with inForm fields larger than 1x1.

To install akoyabio/tiff on Mac you need to install libtiff first. This may help:
https://stackoverflow.com/questions/24775252/r-how-to-install-package-tiff-on-mac-os-x-mavericks
