### ISSUE TITLE
how to download phneoptr/phenoptr reports on Mac?

### ISSUE THREAD

**Issue by db7007** [akoyabio/phenoptr#19]
Respected Sir,

I am new to using R on the MacBook, may I please know how to download it on the Mac?

RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

According to the software documentation, 
1. Install R
Download the most recent version from Cloud.r-project.
2. Mac User: Install Xcode
3. Install RStudio
Download the desktop version of RStudio
4.install.packages("devtools")
devtools::install_github("akoyabio/phenoptr")

I received the following error:

> install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/devtools_2.4.3.tgz'
Content type 'application/x-gzip' length 420183 bytes (410 KB)
==================================================
downloaded 410 KB

The downloaded binary packages are in
	/var/folders/s3/lw6bc3ks4bnff86dq79pn7k00000gn/T//Rtmp3vvRxA/downloaded_packages
> devtools::install_github("akoyabio/phenoptr")
Downloading GitHub repo akoyabio/phenoptr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/akoyabio/phenoptr/tarball/HEAD' failed

**Comment by Deepskyhunter** [comment]
How did you solve the error?
I have encountered the same problem too.
