### ISSUE TITLE
inForm (2.4.4) and Phenoptr

### ISSUE THREAD

**Issue by ArturMez** [akoyabio/phenoptr#2]
Hello!

I got some issues with new inForm (2.4.4).

Phenoptr functions are not working in same way as before with the output from new inForm (using still old approach with MSI scans etc).
For example, read_cell_seg_data command does not read now the txt files properly - it ignores columns containing percentage information (for ex Nuclear Area fraction and confidence).

Also classical R read.table does not seem to deal with these new txt files properly.

Are you aware of these issues or you need more proper explanation of the problem?

All the best,

Artur

**Comment by AB-Kent** [comment]
Hi Artur,

I'm not aware of any problems with phenoptr and the latest inForm. Are you running the latest version of phenoptr? If updating doesn't work, can you send me a file that does not read correctly? Email me at kjohnson@akoyabio.com.

**Comment by AB-Kent** [comment]
This was caused by running inForm in a locale which uses comma as the decimal separator. phenoptr does not read those files. (Base R seems to be pretty tightly bound to the "C" locale.)
