### ISSUE TITLE
'spatial_distribution_report' example is broken

### ISSUE THREAD

**Issue by AB-Kent** [akoyabio/phenoptr#3]
User reports: I'm having trouble running the example of 'spatial_distribution_report' at the bottom of your tutorial here: https://akoyabio.github.io/phenoptr/articles/computing_distances.html

When I try to run that example, I get an error that:

Error in read_cell_seg_data(cell_seg_path, pixels_per_micron = "auto") : 
  To convert cell seg data to microns, a matching component data file is required.

Am I missing the component_data image in the phenoptr package?

**Comment by AB-Kent** [comment]
Yes, this is a bug. When inForm started writing data in microns I started requiring the component data file as an accurate source for spatial data about the cell seg data.

**Comment by LGLGLTM** [comment]
I can confirm this. It doesn't work for the example neither for real inForm data.
It can return that error as well as others (that I didn't take note of).
I managed to output a report with the latest version of Perkin's PhenoptR.

**Comment by AB-Kent** [comment]
@LGLGLTM can you provide more details of the errors you are seeing? `spatial_distribution_report` now requires a component data file to accompany the cell seg data file, is that the cause of your errors?
